version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/
      - ./php/session.ini:/usr/local/etc/php/conf.d/session.ini
      - ./logs/php.log:/var/log/fpm-php.www.log
  memcached:
    image: memcached
    networks:
      - internal
networks:
  internal:
    driver: bridge